site:
  title: OpenShift 101 Workshop
  url: https://showroom-{guid}.apps.{cluster-domain}
  start_page: modules::index.adoc

content:
  sources:
  - url: .
    branches: HEAD
    start_path: content

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
